application: just-landed
version: 2-0
runtime: python27
api_version: 1
threadsafe: true

builtins:
 - remote_api: on
 - appstats: on

inbound_services:
- warmup

libraries:
- name: webapp2
  version: "2.5.1"
- name: webob
  version: "1.1.1"

pagespeed:
  url_blacklist:
  - http://*/api/*
  - http://*/admin/*
  - http://*/cron/*
  - http://*/_ah/*
  - http://*/mapreduce/*
  - https://*/api/*
  - https://*/admin/*
  - https://*/cron/*
  - https://*/_ah/*
  - https://*/mapreduce/*
  enabled_rewriters:
  - InlineJs
  - InlineImages
  - MinifyCss
  - ImageAddDimensions

handlers:
# robots.txt and favicon.ico
- url: /(robots\.txt|favicon\.ico)
  static_files: static/\1
  expiration: "7d"
  upload: static/(.*)

# Static content
- url: /static/(.*)/(-{0,1}[0-9]+)/([^/]+)
  expiration: "7d"
  static_files: static/\1/\3
  upload: static/.*

# Static content directory
- url: /static
  expiration: "7d"
  static_dir: static

# Admin methods that require admin credentials
- url: /admin/.*
  script: main.app
  login: admin
  secure: always

# /_ah other admin urls
- url: /_ah/.*
  script: main.app
  login: admin
  secure: always

# Cron jobs
- url: /cron/.*
  script: main.app
  login: admin
  secure: always

# Map reduce
- url: /mapreduce/pipeline/images
  static_dir: lib/mapreduce/lib/pipeline/ui/images
- url: /mapreduce(/.*)?
  script: lib.mapreduce.main.APP
  login: admin

# Everything else
- url: /.*
  script: main.app

# Custom error handling
error_handlers:
  - file: /static/error_pages/default_error.html
  - error_code: over_quota
    file: /static/error_pages/over_quota.html