application: just-landed
version: 1-0
runtime: python27
api_version: 1
threadsafe: true

# builtins:
# - remote_api: on
# - appstats: on

inbound_services:
- warmup

# Adds memcache and console admin pages to the admin dashboard
admin_console:
  pages:
  - name: Console
    url: /gae-admin/interactive
  - name: Memcache
    url: /gae-admin/memcache

handlers:
# robots.txt and favicon.ico
- url: /(robots\.txt|favicon\.ico)
  static_files: static/\1
  expiration: "30d"
  upload: static/(.*)

# Static content directory
- url: /static
  expiration: "14d"
  static_dir: static

# Additional admin functionality
- url: /gae-admin/.*
  script: google.appengine.ext.admin.application
  login: admin

# Admin methods that require admin credentials
- url: /admin/.*
  script: main.app
  login: admin
  secure: always

# /_ah other admin urls
- url: /_ah/.*
  script: main.app
  login: admin
  secure: always

# ProdEagle stats collection handler
- url: /prodeagle/
  script: lib.prodeagle.harvest.application

# Cron jobs
- url: /cron/.*
  script: main.app
  login: admin
  secure: always

# Everything else
- url: /.*
  script: main.app