application: just-landed
version: 1-0
runtime: python27
api_version: 1
threadsafe: false

builtins:
- remote_api: on

inbound_services:
- warmup

# Generates a Workflows link in admin with graphviz state machine diagrams
admin_console:
  pages:
  - name: Console
    url: /gae-admin/interactive
  - name: Memcache
    url: /gae-admin/memcache

handlers:
# robots.txt and favicon.ico
- url: /(robots\.txt|favicon\.ico)
  static_files: static/\1
  expiration: "30d"
  upload: static/(.*)

# Static content directory
- url: /static
  expiration: "14d"
  static_dir: static

# Additional admin functionality
- url: /gae-admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

# Catch-all
- url: /.*
  script: main.py