application: just-landed
version: 1-2-8
runtime: python27
api_version: 1
threadsafe: true

builtins:
 - remote_api: on
 - appstats: on

inbound_services:
- warmup

handlers:
# robots.txt and favicon.ico
- url: /(robots\.txt|favicon\.ico)
  static_files: static/\1
  expiration: "30d"
  upload: static/(.*)

# Static content directory
- url: /static
  expiration: "14d"
  static_dir: static

# Admin methods that require admin credentials
- url: /admin/.*
  script: main.app
  login: admin
  secure: always

# /_ah other admin urls
- url: /_ah/.*
  script: main.app
  login: admin
  secure: always

# Cron jobs
- url: /cron/.*
  script: main.app
  login: admin
  secure: always

# Everything else
- url: /.*
  script: main.app

# Custom error handling
error_handlers:
  - file: /static/error_pages/default_error.html
  - error_code: over_quota
    file: /static/error_pages/over_quota.html